# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('protocol', models.CharField(max_length=10)),
                ('form_version', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=25, null=True)),
                ('dmis_id', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
